.\" Manpage for rss-youtube-dl.
.\" Contact karlito@martobre.fr to correct errors or typos.
.TH man 1 "22 Apr 2015" "1.0" "rss-youtube-dl man page"
.SH NAME
rss-youtube-dl \- A youtube feed downloader
.SH SYNOPSIS
rss-youtube-dl
.SH DESCRIPTION
rss-youtube-dl is a program designed to automaticaly download the video from the youtube channels you subscribed to.
.SH OPTIONS
The rss-youtube-dl does not take any options.
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Clement Roblot (karlito@martobre.fr)
